// Post-build step: emit dist/sw.js with a precache manifest of every built
// asset (app shell + all baked voice clips) so the installed PWA runs fully
// offline. Zero runtime deps — Workbox et al. are deliberately avoided; this is
// a ~40-line cache-first worker. Re-run automatically by `pnpm build`.
//
// Cache name is content-hashed over the file list, so a new build ships a new
// cache and the activate handler evicts the old one (no Date.now — keeps builds
// reproducible). Nothing here talks to the network at build time.

import { createHash } from "node:crypto";
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const DIST = new URL("../dist/", import.meta.url).pathname;
const BASE = "/"; // matches vite `base`; change both together if you subpath.

/** Recursively list files under dir, as dist-relative POSIX paths. */
function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(relative(DIST, full).split(sep).join("/"));
  }
  return out;
}

const files = walk(DIST)
  .filter((f) => f !== "sw.js") // never precache the worker itself
  .sort();

// URLs to precache: base + each file, plus the base itself (navigation to "/").
const urls = [BASE, ...files.map((f) => BASE + f)];

// Deterministic cache version: hash path + byte size of every asset.
const hash = createHash("sha1");
for (const f of files) hash.update(`${f}:${statSync(join(DIST, f)).size};`);
const version = hash.digest("hex").slice(0, 12);

const sw = `// AUTO-GENERATED by scripts/gen-sw.mjs — do not edit.
const CACHE = "attrape-lettres-${version}";
const ASSETS = ${JSON.stringify(urls)};

self.addEventListener("install", (e) => {
  e.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Cache-first for same-origin GETs. Everything is precached, so this is a hit in
// normal use; the network branch only matters right after a new deploy.
self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  if (new URL(req.url).origin !== self.location.origin) return;
  e.respondWith(
    caches.match(req).then((hit) => {
      if (hit) return hit;
      return fetch(req)
        .then((res) => {
          if (res.ok && res.type === "basic") {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy));
          }
          return res;
        })
        .catch(() => (req.mode === "navigate" ? caches.match("${BASE}") : Response.error()));
    })
  );
});
`;

writeFileSync(join(DIST, "sw.js"), sw);
console.log(`gen-sw: cache attrape-lettres-${version}, ${urls.length} entries precached`);
