package fr.dappit.attrapelettres.art.svg

import java.io.File

// Access to the ONE svg corpus, which lives in the iOS app and is read from
// there — never copied.
//
// `apps/game-ios/Tests/ALArtTests/Resources/svg-corpus.json` holds every `d`
// string that exists in the web app, generated by
// `apps/game-ios/scripts/extract-svg-corpus.mjs` straight out of the TSX and
// SVG sources (template literals have their interpolations replaced with
// sentinel numbers, so the SHAPE of every authored path is covered even though
// the values are synthetic).
//
// One corpus, one home, the same rule the 855 voice-over clips follow: a second
// copy is a second thing to forget to regenerate, and the failure mode is an
// Android build that passes on a corpus the web app stopped having.

/** One row of the corpus. */
data class CorpusEntry(val file: String, val d: String, val kind: String)

object SvgCorpus {

    private val CANDIDATES = listOf(
        // Gradle runs a module's unit tests with the MODULE directory as the
        // working directory, so this is the corpus seen from `:art`.
        "../../game-ios/Tests/ALArtTests/Resources/svg-corpus.json",
        "apps/game-ios/Tests/ALArtTests/Resources/svg-corpus.json",
    )

    /**
     * The corpus file, found by walking up from the test's working directory.
     *
     * The walk is there so that a run from the repo root, or from an IDE with
     * its own idea of a working directory, finds the same one file rather than
     * silently skipping the whole suite. Same shape as `:core`'s `VoManifest`,
     * for the same reason.
     */
    val file: File = run {
        var directory: File? = File("").absoluteFile
        while (directory != null) {
            for (candidate in CANDIDATES) {
                val resolved = File(directory, candidate)
                if (resolved.isFile) return@run resolved
            }
            directory = directory.parentFile
        }
        error("svg-corpus.json not found above ${File("").absoluteFile}")
    }

    private val root: Map<*, *> by lazy { MiniJson.parse(file.readText()) as Map<*, *> }

    /** The `count` field the generator wrote, i.e. how many paths it believes it emitted. */
    val declaredCount: Int by lazy { (root["count"] as Number).toInt() }

    val entries: List<CorpusEntry> by lazy {
        (root["paths"] as List<*>).map { row ->
            val entry = row as Map<*, *>
            CorpusEntry(
                file = entry["file"] as String,
                d = entry["d"] as String,
                kind = entry["kind"] as String,
            )
        }
    }
}

/**
 * A ~90-line JSON reader, because `:art` has no JSON library on its classpath.
 *
 * `:core` keeps `kotlinx-serialization` as an `implementation` dependency, so it
 * does not leak to `:art`, and adding a dependency to read one fixture would be
 * a permanent cost for a test-only need. The corpus is machine-generated, so
 * this only has to read what a generator writes — but it reads escapes properly
 * anyway, because the day a path string contains a quote is not the day to
 * discover a hand-rolled reader.
 */
object MiniJson {

    fun parse(text: String): Any? {
        val reader = Reader(text)
        val value = reader.value()
        reader.skipWhitespace()
        require(reader.atEnd) { "trailing content at ${reader.offset}" }
        return value
    }

    private class Reader(private val text: String) {
        var offset = 0
            private set

        val atEnd: Boolean get() = offset >= text.length

        fun skipWhitespace() {
            while (!atEnd && text[offset].isWhitespace()) offset++
        }

        fun value(): Any? {
            skipWhitespace()
            require(!atEnd) { "unexpected end of input" }
            return when (val c = text[offset]) {
                '{' -> obj()
                '[' -> array()
                '"' -> string()
                't' -> literal("true", true)
                'f' -> literal("false", false)
                'n' -> literal("null", null)
                else -> {
                    require(c == '-' || c in '0'..'9') { "unexpected '$c' at $offset" }
                    number()
                }
            }
        }

        private fun obj(): Map<String, Any?> {
            offset++ // '{'
            val out = LinkedHashMap<String, Any?>()
            skipWhitespace()
            if (!atEnd && text[offset] == '}') {
                offset++
                return out
            }
            while (true) {
                skipWhitespace()
                val key = string()
                skipWhitespace()
                require(!atEnd && text[offset] == ':') { "expected ':' at $offset" }
                offset++
                out[key] = value()
                skipWhitespace()
                require(!atEnd) { "unterminated object" }
                when (text[offset]) {
                    ',' -> offset++
                    '}' -> {
                        offset++
                        return out
                    }

                    else -> error("expected ',' or '}' at $offset")
                }
            }
        }

        private fun array(): List<Any?> {
            offset++ // '['
            val out = ArrayList<Any?>()
            skipWhitespace()
            if (!atEnd && text[offset] == ']') {
                offset++
                return out
            }
            while (true) {
                out.add(value())
                skipWhitespace()
                require(!atEnd) { "unterminated array" }
                when (text[offset]) {
                    ',' -> offset++
                    ']' -> {
                        offset++
                        return out
                    }

                    else -> error("expected ',' or ']' at $offset")
                }
            }
        }

        private fun string(): String {
            require(!atEnd && text[offset] == '"') { "expected a string at $offset" }
            offset++
            val out = StringBuilder()
            while (true) {
                require(!atEnd) { "unterminated string" }
                when (val c = text[offset++]) {
                    '"' -> return out.toString()
                    '\\' -> {
                        require(!atEnd) { "unterminated escape" }
                        when (val e = text[offset++]) {
                            '"' -> out.append('"')
                            '\\' -> out.append('\\')
                            '/' -> out.append('/')
                            'b' -> out.append('\b')
                            'f' -> out.append('\u000C')
                            'n' -> out.append('\n')
                            'r' -> out.append('\r')
                            't' -> out.append('\t')
                            'u' -> {
                                val hex = text.substring(offset, offset + 4)
                                offset += 4
                                out.append(hex.toInt(16).toChar())
                            }

                            else -> error("bad escape '\\$e' at ${offset - 1}")
                        }
                    }

                    else -> out.append(c)
                }
            }
        }

        private fun number(): Double {
            val start = offset
            if (!atEnd && text[offset] == '-') offset++
            while (!atEnd && (text[offset] in '0'..'9' || text[offset] in ".eE+-")) offset++
            return text.substring(start, offset).toDouble()
        }

        private fun literal(word: String, result: Any?): Any? {
            require(text.startsWith(word, offset)) { "bad literal at $offset" }
            offset += word.length
            return result
        }
    }
}
