package fr.dappit.attrapelettres.core.mascot

import fr.dappit.attrapelettres.core.domain.GROWTH_STAGES
import fr.dappit.attrapelettres.core.domain.Species
import kotlin.math.abs
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertSame
import kotlin.test.assertTrue

/**
 * A port of `src/mascot/anchors.test.ts` (2 cases; the first is 50 assertions —
 * 5 species × 10 stades — generated by a loop there and here), plus the iOS
 * additions (`MascotAnchorsTests.swift`).
 *
 * The regression these lock: a neck-worn accessory (ribbon / bell collar / scarf)
 * must sit BELOW the muzzle and stay glued to the head at every stage — never on
 * the face, which is what happened when it was anchored to a body-relative point
 * the baby's oversized head rode over.
 */
class AccessoryAnchorsTest {

    private val stages = 0 until GROWTH_STAGES

    // Upright head (standing): the drawn muzzle reaches ~0.74·headR below the
    // head centre, so the throat must clear that. Lying newborn: the head rests
    // forward & down, so the meaningful floor is just the mouth line (~0.5·headR).
    private val muzzleKStanding = 0.75
    private val mouthK = 0.5

    @Test
    fun `collar sits below the muzzle and on-canvas for every species at every stage`() {
        for (species in Species.entries) {
            for (stage in stages) {
                val layout = layoutFor(stage.toDouble())
                val neck = accessoryAnchors(species, layout).neck
                // Below the muzzle/mouth → not on the face.
                val floor = layout.headCY + layout.headR * (if (layout.standing) muzzleKStanding else mouthK)
                assertTrue(neck.y > floor, "$species stade $stage: collar on the face")
                // Still on the creature (never off the ground line).
                assertTrue(neck.y <= layout.feetY, "$species stade $stage: collar off the creature")
                // Centred on the head's vertical axis (within the head's width).
                assertTrue(abs(neck.x - layout.headCX) <= layout.headR, "$species stade $stage: collar off-axis")
                assertTrue(neck.w > 0, "$species stade $stage: collar width")
            }
        }
    }

    @Test
    fun `hat seat sits above the head, side clip to the upper-left, feet track the legs`() {
        for (species in Species.entries) {
            for (stage in stages) {
                val layout = layoutFor(stage.toDouble())
                val a = accessoryAnchors(species, layout)
                assertTrue(a.headTop.y < layout.headCY) // above the dome
                assertTrue(a.headSide.x < layout.headCX) // upper-left of the face
                assertTrue(a.headSide.y < layout.headCY)
                // `expect(a.feet).toBe(layout.legs)` in the TS is reference
                // identity — the anchors hand back the layout's legs, they do not
                // invent their own. Kotlin can pin exactly that.
                assertSame(layout.legs, a.feet) // boots follow the per-stage legs
            }
        }
    }

    @Test
    fun `feet are the layout's legs, not a fabricated set`() {
        // Pinned a second way, through the count changing with the pose: a lying
        // baby has none.
        for (species in Species.entries) {
            assertTrue(accessoryAnchors(species, layoutFor(0.0)).feet.isEmpty())
            assertTrue(accessoryAnchors(species, layoutFor(1.0)).feet.isEmpty())
            for (stage in 2 until GROWTH_STAGES) {
                assertEquals(4, accessoryAnchors(species, layoutFor(stage.toDouble())).feet.size)
            }
        }
    }

    @Test
    fun `the neck-drop table covers every species with its tuned value`() {
        // The per-muzzle drops are the ONLY species-specific numbers in the file.
        // Totality is the compiler's job here (`when` with no else); the tuned
        // VALUES are this test's.
        // Stade 5 is upright, so neck.y == headCY + headR * NECK_K[species].
        val layout = layoutFor(5.0)
        val want = mapOf(
            Species.UNICORN to 0.9,
            Species.CAT to 0.94, // muzzle sits highest → can drop the most
            Species.FOX to 0.86, // snout sits lowest → drops a touch less
            Species.RABBIT to 0.94, // tiny nose high on the face like the cat
            Species.DRAGON to 0.86, // wide low snout like the fox
        )
        assertEquals(Species.entries.size, want.size)
        for (species in Species.entries) {
            val neck = accessoryAnchors(species, layout).neck
            assertEquals(layout.headCY + layout.headR * want.getValue(species), neck.y, "$species")
        }
        // The fox/dragon really do sit higher than the cat/rabbit — a table
        // collapsed to one constant would pass everything above but not this.
        assertTrue(accessoryAnchors(Species.FOX, layout).neck.y < accessoryAnchors(Species.CAT, layout).neck.y)
    }

    @Test
    fun `the lying newborn's throat is pulled back toward the body`() {
        // Standing and lying are two different formulas, not one with a fudge.
        // The lying throat is pulled BACK toward the body centre; the standing
        // one is straight below the head.
        val baby = layoutFor(0.0)
        assertFalse(baby.standing)
        for (species in Species.entries) {
            val neck = accessoryAnchors(species, baby).neck
            assertEquals((baby.headCX + baby.bodyCX) / 2, neck.x)
            assertTrue(neck.x < baby.headCX) // back toward the body, which is to the left
            assertEquals(baby.headCY + baby.headR * 0.6, neck.y)
            assertEquals(baby.headR * 0.6, neck.w)
            // Species-independent while lying — NECK_K does not apply.
            assertEquals(accessoryAnchors(Species.FOX, baby).neck.y, neck.y)
        }
        val grown = layoutFor(5.0)
        assertTrue(grown.standing)
        assertEquals(grown.headCX, accessoryAnchors(Species.CAT, grown).neck.x)
        assertEquals(grown.headR * 0.7, accessoryAnchors(Species.CAT, grown).neck.w)
    }

    @Test
    fun `anchors track the shrinking head rather than a fixed body point`() {
        // The whole reason this module exists (the "bow in the middle of the
        // face" bug): the anchors are head-relative, so they track the head as
        // it shrinks.
        for (species in Species.entries) {
            var previousOffset = Double.POSITIVE_INFINITY
            for (stage in 2 until GROWTH_STAGES) {
                val l = layoutFor(stage.toDouble())
                val a = accessoryAnchors(species, l)
                assertEquals(l.headR, a.head.r)
                assertEquals(l.headCX, a.head.x)
                assertEquals(l.headCY, a.head.y)
                assertEquals(l.headCY - l.headR, a.headTop.y)
                // The throat-to-head-centre distance shrinks with the head.
                val offset = a.neck.y - l.headCY
                assertTrue(offset < previousOffset, "$species stade $stage")
                previousOffset = offset
            }
        }
    }
}
