import Testing

@testable import ALCore

// Port of `src/mascot/anchors.test.ts` (2 cases; the first is 50 assertions —
// 5 species × 10 stades — generated by a loop there and parameterised here).

/**
 * The regression these lock: a neck-worn accessory (ribbon / bell collar / scarf)
 * must sit BELOW the muzzle and stay glued to the head at every stage — never on
 * the face, which is what happened when it was anchored to a body-relative point
 * the baby's oversized head rode over.
 */

private let allSpecies: [Species] = [.unicorn, .cat, .fox, .rabbit, .dragon]
private let allStages: [Int] = Array(0..<growthStages)

// Upright head (standing): the drawn muzzle reaches ~0.74·headR below the head
// centre, so the throat must clear that. Lying newborn: the head rests forward &
// down, so the meaningful floor is just the mouth line (~0.5·headR).
private let muzzleKStanding = 0.75
private let mouthK = 0.5

@Suite("accessoryAnchors — throat placement clears the face")
struct MascotAnchorsThroatTests {

    @Test(
        "collar below the muzzle, on-canvas",
        arguments: allSpecies, allStages
    )
    func collarBelowTheMuzzleOnCanvas(species: Species, stage: Int) {
        let layout = Growth.layoutFor(Double(stage))
        let neck = accessoryAnchors(species, layout).neck
        // Below the muzzle/mouth → not on the face.
        let floor = layout.headCY + layout.headR * (layout.standing ? muzzleKStanding : mouthK)
        #expect(neck.y > floor)
        // Still on the creature (never off the ground line).
        #expect(neck.y <= layout.feetY)
        // Centred on the head’s vertical axis (within the head’s width).
        #expect(abs(neck.x - layout.headCX) <= layout.headR)
        #expect(neck.w > 0)
    }
}

@Suite("accessoryAnchors — head & feet anchors")
struct MascotAnchorsHeadFeetTests {

    @Test("hat seat sits above the head; side clip to the upper-left; feet track the legs")
    func hatSideAndFeet() {
        for species in allSpecies {
            for stage in allStages {
                let layout = Growth.layoutFor(Double(stage))
                let a = accessoryAnchors(species, layout)
                #expect(a.headTop.y < layout.headCY)  // above the dome
                #expect(a.headSide.x < layout.headCX)  // upper-left of the face
                #expect(a.headSide.y < layout.headCY)
                #expect(a.feet == layout.legs)  // boots follow the per-stage legs
            }
        }
    }

    /// `a.feet === layout.legs` in the TS is reference identity. Swift arrays are
    /// values, so identity is not a thing to assert — what the TS was really
    /// pinning is that the anchors do not invent their own legs. Pinned instead
    /// by the count changing with the pose: a lying baby has none.
    @Test("feet are the layout's legs, not a fabricated set")
    func feetAreTheLayoutsLegs() {
        for species in allSpecies {
            #expect(accessoryAnchors(species, Growth.layoutFor(0)).feet.isEmpty)
            #expect(accessoryAnchors(species, Growth.layoutFor(1)).feet.isEmpty)
            for stage in 2..<growthStages {
                #expect(accessoryAnchors(species, Growth.layoutFor(Double(stage))).feet.count == 4)
            }
        }
    }
}

@Suite("accessoryAnchors — the species table and the two placement modes")
struct MascotAnchorsSpeciesTableTests {

    /// The per-muzzle drops are the ONLY species-specific numbers in the file,
    /// and an optional lookup that missed would silently draw a collar on the
    /// chin. This asserts the table is total and holds the tuned values.
    @Test("the neck-drop table covers every species with its tuned value")
    func neckDropTableIsTotal() {
        // Stade 5 is upright, so neck.y == headCY + headR * NECK_K[species].
        let layout = Growth.layoutFor(5)
        let want: [Species: Double] = [
            .unicorn: 0.9,
            .cat: 0.94,  // muzzle sits highest → can drop the most
            .fox: 0.86,  // snout sits lowest → drops a touch less
            .rabbit: 0.94,  // tiny nose high on the face like the cat
            .dragon: 0.86,  // wide low snout like the fox
        ]
        #expect(want.count == Species.allCases.count)
        for species in Species.allCases {
            let neck = accessoryAnchors(species, layout).neck
            #expect(neck.y == layout.headCY + layout.headR * want[species]!, "\(species)")
        }
        // The fox/dragon really do sit higher than the cat/rabbit — a table
        // collapsed to one constant would pass everything above but not this.
        #expect(accessoryAnchors(.fox, layout).neck.y < accessoryAnchors(.cat, layout).neck.y)
    }

    /// Standing and lying are two different formulas, not one with a fudge.
    /// The lying throat is pulled BACK toward the body centre; the standing one
    /// is straight below the head.
    @Test("the lying newborn's throat is pulled back toward the body")
    func lyingThroatIsPulledBack() {
        let baby = Growth.layoutFor(0)
        #expect(!baby.standing)
        for species in allSpecies {
            let neck = accessoryAnchors(species, baby).neck
            #expect(neck.x == (baby.headCX + baby.bodyCX) / 2)
            #expect(neck.x < baby.headCX)  // back toward the body, which is to the left
            #expect(neck.y == baby.headCY + baby.headR * 0.6)
            #expect(neck.w == baby.headR * 0.6)
            // Species-independent while lying — NECK_K does not apply.
            #expect(neck.y == accessoryAnchors(.fox, baby).neck.y)
        }
        let grown = Growth.layoutFor(5)
        #expect(grown.standing)
        #expect(accessoryAnchors(.cat, grown).neck.x == grown.headCX)
        #expect(accessoryAnchors(.cat, grown).neck.w == grown.headR * 0.7)
    }

    /// The whole reason this module exists (the "bow in the middle of the face"
    /// bug): the anchors are head-relative, so they track the head as it shrinks.
    @Test("anchors track the shrinking head rather than a fixed body point")
    func anchorsTrackTheHead() {
        for species in allSpecies {
            var previousOffset = Double.infinity
            for stage in 2..<growthStages {
                let l = Growth.layoutFor(Double(stage))
                let a = accessoryAnchors(species, l)
                #expect(a.head.r == l.headR)
                #expect(a.head.x == l.headCX)
                #expect(a.head.y == l.headCY)
                #expect(a.headTop.y == l.headCY - l.headR)
                // The throat-to-head-centre distance shrinks with the head.
                let offset = a.neck.y - l.headCY
                #expect(offset < previousOffset, "\(species) stade \(stage)")
                previousOffset = offset
            }
        }
    }
}
